### ISSUE TITLE
Possible conflict with the Dynamic Prompts extension

### ISSUE THREAD

**Issue by artyfacialintelagent** [artyfacialintelagent/CloneCleaner#4]
Reported on Reddit:
https://www.reddit.com/r/StableDiffusion/comments/14jl0er/ann_clonecleaner_a_new_extension_for_auto1111_to/jpnnfof/

**Comment by enzyme69** [comment]
I kind of like Dynamic Prompts saving the list of generated files prompt as csv. 

I also think it might be clashing, but so far I can't get CloneCleaner to work, the UI is locked.

**Comment by artyfacialintelagent** [comment]
Duplicate of #1, closing in favor of that issue.
